.config/emacs:
  type: git-repo
  url: "https://github.com/doomemacs/doomemacs.git"
  refreshPeriod: "168h"
.config/alacritty/catppuccin-mocha.toml:
  type: file
  url: "https://github.com/catppuccin/alacritty/raw/main/catppuccin-mocha.toml"
  refreshPeriod: "168h"
