.config/emacs:
  type: git-repo
  url: "https://github.com/doomemacs/doomemacs.git"
  refreshPeriod: "168h"
.config/alacritty/catppuccin-mocha.toml:
  type: file
  url: "https://github.com/catppuccin/alacritty/raw/main/catppuccin-mocha.toml"
  refreshPeriod: "168h"
.config/bat/themes/Catppuccin Mocha.tmTheme:
  type: file
  url: "https://github.com/catppuccin/bat/raw/refs/heads/main/themes/Catppuccin%20Mocha.tmTheme"
  refreshPeriod: "168h"
