call pathogen#infect()
call pathogen#helptags()
syntax on
filetype plugin indent on

" Reset leader (default \)
let mapleader=","

" Don't have to be vi-compatible
set nocompatible

set number
" If you would like numbers relative to your current line
" set relativenumber
set ruler

" Set default encoding
set encoding=utf-8

" Whitespace stuff
set nowrap
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set list listchars=tab:▸\ ,eol:¬,trail:•

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase
set gdefault " automatically set "/g" at the end of :substution commands
nnoremap / /\v
vnoremap / /\v

" Auto formatting
set autoindent " automatically indent text
set formatoptions+=n1 " add formatting numbered list to autoformat

" Spelling options
set spell spelllang=en_us

" Moving around windows
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

"Misc
set ttyfast " using a fast terminal
nnoremap ; :
inoremap jj <ESC>

" Tab completion
set wildmode=list:longest,list:full
set wildignore+=*.o,*.obj,.git,*.rbc,*.class,.svn,vendor/gems/*

" Status bar
set laststatus=2

" Remember last location in file
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal g'\"" | endif
endif

function s:setupWrapping()
  set wrap
  set wrapmargin=2
  set textwidth=72
 endfunction

 " make uses real tabs
 au FileType make set noexpandtab

 " Thorfile, Rakefile, Vagrantfile and Gemfile are Ruby
 au BufRead,BufNewFile {Gemfile,Rakefile,Vagrantfile,Thorfile,config.ru} set ft=ruby

 au BufRead,BufNewFile {*.md} set ft=markdown

 au BufRead,BufNewFile *.txt call s:setupWrapping()

 " Make Python follow PEP8 ( http://www.python.org/dev/peps/pep-0008 )
 au FileType python set softtabstop=4 tabstop=4 shiftwidth=4 textwidth=79

 " Allow backspacing over everything in insert mode
 set backspace=indent,eol,start

 " remap <F1> to turning off search highlighting (default: help)
 map <F1> :nohl<CR>
 imap <F1> <ESC>:nohl<CR> i

 " Use modeline overrides
 set modeline
 set modelines=10

 " Directories for swp files
 set backupdir=~/.vim/backup
 set directory=~/.vim/backup
 if version >= 703
   set undofile
   set undodir=~/.vim/undo
 endif

 " Reformat the current paragraph according to current 'textwidth' with ^]
 nmap <C-]> gqap
 vmap <C-]> gq
 imap <C-]> <C-O>gqap

 " Tabs
 map <Leader>tp :tabp<CR>
 map <Leader>tn :tabnext<CR>

 " Show (partial) command in the status line
 set showcmd

 colorscheme Tomorrow-Night
 set background=dark

 " ctrlp settings
 let g:ctrlp_working_path_mode = 0 " always relative to root
